### PR TITLE
fix: Handling Package Dependency Callback for Insights v2 Package Met…

### LINKED ISSUE #307: Fix Bug Handling Package Dependency Callback for Insights v2 Package Meta Enricher

### PR DESCRIPTION
**Pull request by KunalSin9h**
…a Enricher

fixes #307

### CODE REVIEW

File: pkg/scanner/enrich_insightsv2.go [hunk 1]
```diff
@@ -61,7 +61,32 @@ func (e *insightsBasedPackageEnricherV2) Enrich(pkg *models.Package,
...
+		if strings.EqualFold(dep.GetPackage().Name, pkg.GetName()) {
+			// Skip cyclic references
+			continue
+		}
+
+		if err := cb(&models.Package{
+			Manifest: pkg.Manifest,
+			Parent:   pkg,
+			Depth:    pkg.Depth + 1,
+			PackageDetails: models.NewPackageDetail(dep.GetPackage().GetEcosystem().String(),
```
Comment (abhisek) [inline pkg/scanner/enrich_insightsv2.go:82]: This will not work because we have mapping of ecosystem standard names. You probably need to use: https://github.com/safedep/vet/blob/main/pkg/models/models.go#L281

**Comment by KunalSin9h** [comment]
@abhisek i have resolved it, can you review

**Review by abhisek — APPROVED** [review]
