### PR TITLE
Fix CycloneDX SBOM validation

### LINKED ISSUE #637: SBOM Report Produces non-compliant SBOM
## Background

User reported issue:

> Using the sbom generated by vet. Using this to validate the schema https://cyclonedx.github.io/cyclonedx-web-tool/validate

## Requirement

`vet` should produce SBOM that is valid and verifiable using official SBOM schema validator.

### PR DESCRIPTION
**Pull request by Sahilb315**
Fixes #637

### CODE REVIEW

File: pkg/reporter/cyclonedx.go [hunk 1]
```diff
@@ -110,6 +111,7 @@ func NewCycloneDXReporter(config CycloneDXReporterConfig) (Reporter, error) {
 		rootComponentBomref:       rootComponentBomref,
 		bomEcosystems:             map[string]bool{},
 		bomVulnerabilitiesBomrefs: map[string]bool{},
+		bomPackageRef:             map[string]struct{}{},
```
Comment (abhisek) [inline pkg/reporter/cyclonedx.go]:
```suggestion
		bomPackageRef:             map[string]bool{},
```

Lets just do bool like the others please.

File: pkg/reporter/cyclonedx.go [hunk 2]
```diff
@@ -188,15 +199,9 @@ func (r *cycloneDXReporter) resolvePackageLicenses(pkg *models.Package) []cdx.Li
 	for _, license := range *pkg.Insights.Licenses {
 		licenseChoice := cdx.LicenseChoice{
 			License: &cdx.License{
-				Name: string(license),
```
Comment (abhisek) [inline pkg/reporter/cyclonedx.go:191]: What is the issue with name? Does the spec says not to have name?

File: pkg/reporter/cyclonedx.go [hunk 3]
```diff
@@ -188,15 +199,9 @@ func (r *cycloneDXReporter) resolvePackageLicenses(pkg *models.Package) []cdx.Li
...
-				ID:   string(license),
+				ID: string(license),
 			},
 		}
-		spdxLicense, availableSpdxLicense := data.SpdxLicenses[string(license)]
-		if availableSpdxLicense {
```
Comment (abhisek) [inline pkg/reporter/cyclonedx.go:196]: We should have these license metadata if available right? What does the CycloneDX spec says?

File: pkg/reporter/cyclonedx_test.go [hunk 4]
```diff
@@ -285,8 +285,6 @@ func TestCycloneDxReporterLicenses(t *testing.T) {
 	licenses := utils.SafelyGetValue(utils.SafelyGetValue(generatedBom.Components)[0].Licenses)
 	assert.Len(t, licenses, 1)
 	assert.Equal(t, "MIT", licenses[0].License.ID)
-	assert.Equal(t, "MIT License", licenses[0].License.Name)
```
Comment (abhisek) [inline pkg/reporter/cyclonedx_test.go:288]: Not sure if we should just remove them.

File: pkg/reporter/cyclonedx.go (hunk 2 above)
Comment (Sahilb315) [reply pkg/reporter/cyclonedx.go:191]: Yeah, Only one of `ID` or `Name` can be present. No other values can be present.

Schema to verify: https://cyclonedx.org/schema/bom-1.6.schema.json
You can search for `"license":` to find the licenses schema

File: pkg/reporter/cyclonedx.go (hunk 3 above)
Comment (Sahilb315) [reply pkg/reporter/cyclonedx.go:196]: Only one of `ID` or `Name` can be present. No other values can be present.

Schema to verify: https://cyclonedx.org/schema/bom-1.6.schema.json
You can search for `"license":` to find the licenses schema

**Review by abhisek — APPROVED** [review]
